"""Reusable Streamlit pieces: CSS, metric cards, status banner, alert log."""
from __future__ import annotations

import html

import numpy as np
import pandas as pd
import streamlit as st

from src.prediction.alerts import AlertState
from src.prediction.remaining_time import format_hms, format_hours_minutes

STATUS_COLORS = {"NORMAL": "#2e7d32", "WARNING": "#ed6c02",
                 "CRITICAL": "#c62828", "UNKNOWN": "#616161"}

CSS = """<style>
.iv-card{border:1px solid rgba(128,128,128,.35);border-radius:12px;padding:12px 16px;
background:rgba(128,128,128,.08);margin-bottom:12px;min-height:104px}
.iv-label{font-size:.76rem;letter-spacing:.05em;text-transform:uppercase;opacity:.7}
.iv-value{font-size:1.55rem;font-weight:650;line-height:1.3}
.iv-sub{font-size:.78rem;opacity:.65}
.iv-banner{border-radius:12px;padding:14px 20px;margin:6px 0 16px 0;color:#fff}
.iv-status{font-size:1.4rem;font-weight:700;letter-spacing:.04em}
.iv-msg{font-size:.95rem;opacity:.95}
.iv-disclaimer{border:1px dashed rgba(128,128,128,.6);border-radius:8px;padding:6px 12px;
font-size:.82rem;opacity:.85;margin-bottom:10px}
</style>"""


def inject_css() -> None:
    st.markdown(CSS, unsafe_allow_html=True)


def disclaimer() -> None:
    st.markdown(
        '<div class="iv-disclaimer"><b>SOFTWARE SIMULATION / PROTOTYPE.</b> All sensor data are '
        'generated by Python. This is not a medical device and must not be used for patient care.'
        '</div>', unsafe_allow_html=True)


def fmt_num(x, fmt: str = "{:.1f}", unit: str = "") -> str:
    """Format a number, or 'n/a' for None / NaN / non-numbers."""
    try:
        v = float(x)
    except (TypeError, ValueError):
        return "n/a"
    if not np.isfinite(v):
        return "n/a"
    return fmt.format(v) + (f" {unit}" if unit else "")


def card_html(label: str, value: str, sub: str = "", accent: str | None = None) -> str:
    style = f' style="color:{accent}"' if accent else ""
    return (f'<div class="iv-card"><div class="iv-label">{html.escape(label)}</div>'
            f'<div class="iv-value"{style}>{html.escape(value)}</div>'
            f'<div class="iv-sub">{html.escape(sub)}</div></div>')


def status_banner(state: AlertState) -> None:
    color = STATUS_COLORS.get(state.status, STATUS_COLORS["UNKNOWN"])
    extra = "   |   SENSOR DISAGREEMENT" if state.disagreement_alert else ""
    st.markdown(
        f'<div class="iv-banner" style="background:{color}">'
        f'<div class="iv-status">SYSTEM STATUS: {html.escape(state.status)}{html.escape(extra)}</div>'
        f'<div class="iv-msg">{html.escape(state.message)}</div></div>',
        unsafe_allow_html=True)


def metric_grid(row: pd.Series, cfg) -> None:
    """3 x 3 grid of cards for the latest window."""
    win = cfg.preprocessing.window_size_s
    completion = row["completion_time"]
    flag = bool(row["disagreement_alert"])
    vol_note = ("from load-cell weight" if bool(row["volume_from_weight"])
                else "estimated (weight sample missing)")

    cards = [
        [("Current bag weight", fmt_num(row["weight_g"], "{:.1f}", "g"),
          "total, including the empty bag"),
         ("Remaining volume", fmt_num(row["remaining_volume_ml"], "{:.0f}", "mL"), vol_note),
         ("Estimated flow rate (EKF)", fmt_num(row["flow_ekf"], "{:.2f}", "mL/min"),
          f"uncertainty +/- {fmt_num(row['flow_std'], '{:.2f}')} (1 sigma)")],
        [("Drop rate", fmt_num(row["drop_rate_per_min"], "{:.1f}", "drops/min"),
          f"IR count over a {win:.0f} s window"),
         ("Estimated drop factor (EKF)", fmt_num(row["drop_factor_ekf"], "{:.2f}", "drops/mL"),
          f"+/- {fmt_num(row['drop_factor_std'], '{:.2f}')}; printed on tubing: "
          f"{cfg.drop_sensor.nominal_drop_factor:g}"),
         ("Remaining time", format_hms(row["remaining_time_min"]),
          format_hours_minutes(row["remaining_time_min"]))],
        [("Predicted completion",
          completion.strftime("%H:%M:%S") if pd.notna(completion) else "n/a",
          completion.strftime("%Y-%m-%d (simulated clock)") if pd.notna(completion) else ""),
         ("95% confidence interval",
          f"{format_hms(row['ci_low_min'])} - {format_hms(row['ci_high_min'])}",
          f"sigma of remaining time = {fmt_num(row['sigma_T_min'], '{:.1f}')} min"),
         ("Sensor disagreement",
          fmt_num(100.0 * row["disagree_rel"], "{:.1f}", "%"),
          f"weight {fmt_num(row['flow_weight_ml_min'], '{:.2f}')} vs drops "
          f"{fmt_num(row['flow_drop_ml_min'], '{:.2f}')} mL/min")],
    ]
    for line in cards:
        cols = st.columns(3)
        for col, (label, value, sub) in zip(cols, line):
            accent = STATUS_COLORS["CRITICAL"] if (label == "Sensor disagreement" and flag) else None
            col.markdown(card_html(label, value, sub, accent), unsafe_allow_html=True)


def alert_log(vis: pd.DataFrame) -> pd.DataFrame:
    """Table of alert events so far: status changes and the start of disagreement alerts."""
    status = vis["alert_status"].astype(str)
    changed = status != status.shift()
    flag = vis["disagreement_alert"].astype(bool)
    onset = flag & ~flag.shift(fill_value=False)

    events = []
    for _, r in vis[changed].iterrows():
        events.append((r["t_end_s"] / 60.0, f"Status: {r['alert_status']}",
                       format_hms(r["remaining_time_min"])))
    for _, r in vis[onset].iterrows():
        events.append((r["t_end_s"] / 60.0, "Sensor disagreement started",
                       format_hms(r["remaining_time_min"])))
    events.sort(key=lambda e: e[0])
    return pd.DataFrame(events, columns=["Time (min)", "Event", "Remaining time"]).round(
        {"Time (min)": 1})


def show_plot(fig) -> None:
    """st.plotly_chart across Streamlit versions (the width argument was renamed)."""
    try:
        st.plotly_chart(fig, width="stretch")
    except Exception:  # older Streamlit
        st.plotly_chart(fig, use_container_width=True)